### ISSUE TITLE
Bot trying to verify comments as Post

### ISSUE THREAD

**Issue by ikhaled28** [Wag-Media/wagmedia-com-bot#40]
The BOT is trying to verify post comments for for the Title, Description pattern. Is it necessary?

**Comment by niklasp** [comment]
Logically it is necessary as every message can be a potential post.

Except we introduce rules for what can never be a post.

But also of couse it can just be quiet and not log qnything. That we need to decide

**Comment by ikhaled28** [comment]
We will discuss again after seeing how it behaves with payments.
