### ISSUE TITLE
BOT need to listen/track old posts based on special emoji.

### ISSUE THREAD

**Issue by ikhaled28** [Wag-Media/wagmedia-com-bot#41]
an emoji that is added to a post that was BEFORE bot joined. but in order to trigger that we need a logic, e.g. add one special emoji ORRRR check on ANY wagMedia reaction, if the website and discord are in sync.

**Comment by niklasp** [comment]
on it

**Comment by niklasp** [comment]
fixed in class ReactionDiscrepancyResolver
