### ISSUE TITLE
Do not handle rules for external Discord Server emojis

### ISSUE THREAD

**Issue by niklasp** [Wag-Media/wagmedia-com-bot#42]
only wagmedia specific emojis should trigger rules. all others should just be recorded.

**Comment by niklasp** [comment]
@ikhaled28 i checked the bot code and am 90% sure it does not process external emojis (e.g. an "50WMUSD" emoji from another server would be recorded but not trigger a payment). Is this the desired behavior or should something else happen?

**Comment by ikhaled28** [comment]
Yes it related to Payment emojis. So to be more clear, do not record anything which contains the same name like our Payment emojis. Rest can be ok. If those payment emojis comes from external server just remove those, as It might give scammer a chance for fraud claims.

**Comment by niklasp** [comment]
hmm. i cannot remove only "payment emojis" from external servers, anyone can name their emojis how they wish and use our images for it. what i can do is disallow all external emojis on monitored channels? or just dont do anything. 

I mean it is misleading to see some payment emojis looking the same but as they will trigger no payment it doesnt matter? just confuse

**Comment by ikhaled28** [comment]
> hmm. i cannot remove only "payment emojis" from external servers, anyone can name their emojis how they wish and use our images for it. what i can do is disallow all external emojis on monitored channels? or just dont do anything.
> 
> I mean it is misleading to see some payment emojis looking the same but as they will trigger no payment it doesnt matter? just confuse

yeah you are right. Can we just not read the same name then. Like if we see an external emoji named same like our server one then we can ignore it anyway, that will do for us.

**Comment by ikhaled28** [comment]
Yeah, ignore the issue. Close the issue for now
