### ISSUE TITLE
Zero reward post but reviewers need to receive Payment for their review.

### ISSUE THREAD

**Issue by ikhaled28** [Wag-Media/wagmedia-com-bot#43]
We need to design a system where the original post won't be published to the website, nor it will receive any rewards. But the reviewers will receive their rewards.

**Comment by niklasp** [comment]
@ikhaled28 what do you mean exactly? does it translate to:
- thread payments should be possible even when parent post is not published / paid?

**Comment by ikhaled28** [comment]
> @ikhaled28 what do you mean exactly? does it translate to:
> 
> * thread payments should be possible even when parent post is not published / paid?

Yes, the logic can be:

Director reacts with ❌, then the post's thread comments can receive rewards for their comments.

**Comment by niklasp** [comment]
only then?

**Comment by ikhaled28** [comment]
> only then?
Make the feature available for both 
❌ and 
![WMZERODOTPUB](https://github.com/Wag-Media/wagmedia-com-bot/assets/1229899/cb2fd547-a2b6-4480-bdb4-5d543246c97e)

The reviewers (thread commenters will receive their rewards for reviewing the content).

**Comment by ikhaled28** [comment]
For the audit section please save the data. 

❌: 
1. keep the Discord link of the post and comment, as there won't be any website post.

**Comment by niklasp** [comment]
thats automatic if the post is valid = following the tile: description: format

**Comment by ikhaled28** [comment]
Yes
