### ISSUE TITLE
Categories for payment/salary types

### ISSUE THREAD

**Issue by niklasp** [Wag-Media/wagmedia-com-bot#64]
only allow certain cateogires for oddjobs in "Role".

**Comment by niklasp** [comment]
@ikhaled28 please add the allowed roles here

**Comment by ikhaled28** [comment]
**Website and Discord Bot Development**
1. Developer
2. QA and Product Owner
3. QA 
4. Product Owner
5. WagTool
6. Infra
7. Designer

**Management / Team**
1. Director
2. Social Media
3. Intern
4. Treasury Management

**Marketing**
1. Ads
2. KaitoAI
3. Analytics
